# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install Hugo 
      run: brew install hugo

    # Runs a set of commands using the runners shell
    - name: Display hugo version
      run: |
        hugo version
    
    - name: Create hugo site 
      run : |
        hugo new site quickstart
        cd quickstart    
        git init 
        git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
        echo 'theme = "ananke"' >> config.toml
        hugo new posts/my-first-post.md
        hugo -D
     - name: Deploy public folder
       run: | 
         cd public    
         ls -l 
        
      
    
